### ISSUE TITLE
ms not defined

### ISSUE THREAD

**Issue by dreavega** [makbit/LED7Segments#1]
really nice tutorial: http://makbit.com/web/firmware/how-to-drive-4-digit-7-segment-led-display-with-arduino/
but I keep getting an error when trying to upload this sketch, because ms is not defined.
    if( millis() / 1000 > ms )

halp plz? 

-noob

**Comment by makbit** [comment]
Hello friend!
In the tutorial the variable "ms" was not declared. I have fixed this error in the tutorial.  http://makbit.com/web/firmware/how-to-drive-4-digit-7-segment-led-display-with-arduino/
Thank you.
However the github version is correct.

**Comment by dreavega** [comment]
Great, thank you for the help!
